apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - ../base
helmCharts:
  - name: openclaw
    releaseName: openclaw
    namespace: openclaw
    path: ../../charts/openclaw
    valuesFile: values-prod.yaml
