{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclaw.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
