{{- $p := .Values.persistence.config -}}
{{- if and $p.enabled (not $p.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-config" (include "openclaw.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml $p.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $p.size }}
  {{- if $p.storageClass }}
  storageClassName: {{ $p.storageClass | quote }}
  {{- end }}
{{- end -}}
