{{- if and .Values.secret.create (not (empty .Values.secret.stringData)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw.secretName" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end -}}
